# Generated by Django 3.2.25 on 2024-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20240518_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvite',
            name='accepted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='gameinvite',
            name='rejected',
            field=models.BooleanField(default=0),
        ),
    ]
