# Generated by Django 3.2.25 on 2024-05-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240518_1431'),
        ('game', '0004_auto_20240518_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='core.person'),
        ),
        migrations.AlterField(
            model_name='gameinvite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='core.person'),
        ),
    ]
