# Generated by Django 3.2.24 on 2024-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
