# Generated by Django 3.2.24 on 2024-02-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dummy_field',
        ),
    ]
