# Generated by Django 3.2.24 on 2024-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picture',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
