# Generated by Django 3.2.24 on 2024-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240224_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
