# Generated by Django 3.2.25 on 2024-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
