# Generated by Django 3.2.25 on 2024-03-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_person_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_players', models.IntegerField(default=2)),
                ('live', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('random', 'Random')], default='light', max_length=50)),
                ('gamemode', models.CharField(choices=[('easy', 'Easy'), ('classic', 'Classic'), ('hard', 'Hard')], default='easy', max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('players', models.ManyToManyField(blank=True, related_name='joined_players', to='core.Person')),
            ],
        ),
    ]
