# Generated by Django 3.2.25 on 2024-03-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gameroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
