# Generated by Django 3.2.25 on 2024-03-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gameroom_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ongoing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_in_game', to='core.gameroom'),
        ),
    ]
