# Generated by Django 3.2.25 on 2024-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_person_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
