# Generated by Django 3.2.25 on 2024-04-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gameroom_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='game_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
