# Generated by Django 3.2.25 on 2024-04-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='twofactor',
            field=models.BooleanField(default=False),
        ),
    ]
