# Generated by Django 3.2.25 on 2024-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
