# Generated by Django 3.2.25 on 2024-05-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_history_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='model',
            new_name='gamemode',
        ),
    ]
